# First Assignment: Numpy

The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

Please follow this assignment through the following exercises to get familiar with numpy. It is a very interesting library. So, Take a deep breathe and let's start :)

Let's import numpy as you learned and give it an alias as np. Write your code into the next cell. To run the following cell after writing your code, just press (Shift + Enter).

In [1]:
# expected a single line of code
import numpy as np
# end of code
np.version.short_version

'1.14.3'

If the version your installed numpy is just printed, then you are doing great. But if you saw an error, just try again or search google for how to import numpy as np.

### 1. Creating Arrays

Now, Create an array with the following values [1, 2, 3] and name it as 'a'.

In [2]:
# write your code here (~ 1 line of code)
a = np.array([1, 2, 3])
#end of code
print('a = ', a)

a =  [1 2 3]


Create a 2D array of shape (4,5) with arbitrary integer entries.

In [10]:
# write your code here (~ 1 line of code)
b = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
#end of code
print('b = \n', b)

b = 
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


Create a 3D array with arbitrary floaing point input and set the array data type into float.

In [23]:
# write your code here (~ 1 line of code)
c = np.zeros((2,3,3))
#end of code
print('c = \n', c)

c = 
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


Create an array of zeros with shape of (3,4)

In [28]:
# write your code here (~ 1 line of code)
z = np.zeros((3,4))
#end of code
print('z = \n', z)

z = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Create an array of ones with shape of (5,4)

In [30]:
# write your code here (~ 1 line of code)
o = np.ones((5,4))
#end of code
print('o = \n', o)

o = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Create an array of 7's with shape of (9,7)

In [32]:
# write your code here (~ 1 line of code)
const = np.ones((9,7)) *7
#end of code
print('const = \n', const)

const = 
 [[7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7.]]


Create 4 x 4 identity matrix

In [34]:
# write your code here (~ 1 line of code)
i = np.eye(4)
#end of code
print('i = \n', i)

i = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Create an array of shape (4,5)  with radom entries 

In [113]:
# write your code here (~ 1 line of code)
r = np.random.randn(4,5)
#end of code
print('r = \n', r)

r = 
 [[ 1.38929058  1.80730647  1.00146972 -1.69803038 -2.01050893]
 [-0.56845801  0.95160039  0.24338586 -1.41281285 -0.39722562]
 [ 1.99804627 -0.94393919  0.63238182 -1.25188772  0.0833394 ]
 [ 1.51049691  0.47203351  0.80153071  0.42882538 -0.86378836]]


### 2. Inspecting your array

Print the dimentions of array (a)

In [116]:
# write your code here (~ 1 line of code)
dim = np.shape(a)
#end of code
print('dim (shape) of a = ', dim)

dim (shape) of a =  (3,)


Print the number of dimentions of array (b)

In [48]:
# write your code here (~ 1 line of code)
dim_num = np.shape(b)
#end of code
print('number of dim of b = ', dim_num)

number of dim of b =  (4, 5)


Print the data type of elements in array c

In [83]:
# write your code here (~ 1 line of code)
dtype = c.dtype
#end of code
print('data type of elements in array c is ', dtype)

data type of elements in array c is  float64


Print the number of elements in array i

In [77]:
# write your code here (~ 1 line of code)
elements_num = np.size(i)
#end of code
print('number of elements in array i = ', elements_num)

number of elements in array i =  16


Convert the array named const from int into float

In [89]:
# write your code here (~ 1 line of code)
const = const.astype(float)
#end of code
print('const = ', const.dtype)

const =  float64


### 3. Array Mathematics

Subtract b from r

In [118]:
# write your code here (~ 1 line of code)
g = r - b
#end of code
print('g = r - b = \n', g)

g = r - b = 
 [[ 0.38929058 -0.19269353 -1.99853028 -5.69803038 -7.01050893]
 [-1.56845801 -1.04839961 -2.75661414 -5.41281285 -5.39722562]
 [ 0.99804627 -2.94393919 -2.36761818 -5.25188772 -4.9166606 ]
 [ 0.51049691 -1.52796649 -2.19846929 -3.57117462 -5.86378836]]


Add b + r

In [120]:
# write your code here (~ 1 line of code)
s = b + r
#end of code
print('s = b + r = ', s)

s = b + r =  [[2.38929058 3.80730647 4.00146972 2.30196962 2.98949107]
 [0.43154199 2.95160039 3.24338586 2.58718715 4.60277438]
 [2.99804627 1.05606081 3.63238182 2.74811228 5.0833394 ]
 [2.51049691 2.47203351 3.80153071 4.42882538 4.13621164]]


Multiply b by r (element wise multiplication)

In [122]:
# write your code here (~ 1 line of code)
m = r * b
#end of code
print('m = b * r = \n', m)

m = b * r = 
 [[  1.38929058   3.61461295   3.00440916  -6.7921215  -10.05254465]
 [ -0.56845801   1.90320077   0.73015758  -5.6512514   -1.98612809]
 [  1.99804627  -1.88787839   1.89714545  -5.00755088   0.41669699]
 [  1.51049691   0.94406701   2.40459212   1.7153015   -4.31894179]]


Divide r by b (element wise divition)

In [124]:
# write your code here (~ 1 line of code)
d = r / b
#end of code
print('d = r / b = \n', d)

d = r / b = 
 [[ 1.38929058  0.90365324  0.33382324 -0.42450759 -0.40210179]
 [-0.56845801  0.47580019  0.08112862 -0.35320321 -0.07944512]
 [ 1.99804627 -0.4719696   0.21079394 -0.31297193  0.01666788]
 [ 1.51049691  0.23601675  0.2671769   0.10720634 -0.17275767]]


### 4. Comparison

Find elements where b(i) == r(i)

In [126]:
# write your code here (~ 1 line of code)
res_bool = (b == r)
#end of code
print('elements where b = r are ', b[res_bool])

elements where b = r are  []


Find elements in c where c(i) < 3

In [130]:
# write your code here (~ 2 line of code)
res_bool = (c < 3)
print('elements in c that are less than 3 are \n', c[None])
#end of code

elements in c that are less than 3 are 
 [[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]


### 5. Aggregate Functions

Find sum of a

In [131]:
# write your code here (~ 1 line of code)
s = sum(a)
#end of code
print('sum of a = ', s)

sum of a =  6


Find min of b

In [134]:
# write your code here (~ 1 line of code)
m = np.min(b)
#end of code
print('min of b = ', m)

min of b =  1


Find max of c

In [135]:
# write your code here (~ 1 line of code)
m = np.max(c)
#end of code
print('max of c = ', m)

max of c =  0.0


Find mean of r

In [136]:
# write your code here (~ 1 line of code)
m = np.mean(r)
#end of code
print('mean of r = ', m)

mean of r =  0.10865279707744402


Find stadard deviation of r

In [137]:
# write your code here (~ 1 line of code)
s = np.std(r)
#end of code
print('std of r = ', s)

std of r =  1.1675765251535788


Coppy array a into aa

In [139]:
# write your code here (~ 1 line of code)
aa = np.copy(a)
#end of code
aa *= 2
print('Wrong trial. Please try again') if np.array_equal(a, aa) else print('correctly coppied')

correctly coppied


Sort array a

In [141]:
# write your code here (~ 1 line of code)
a = np.sort(a)
#end of code
print('a = ', a) 

a =  [1 2 3]


Sort the elements of array's axis 0 (array a)

In [142]:
# write your code here (~ 1 line of code)
a = np.sort(a, axis=0)
#end of code
print('a = ', a)

a =  [1 2 3]


### 6. Subsetting, Slicing, Indexing

Change the all values of second column of b into 6

In [145]:
# write your code here (~ 1 line of code)
b[1, :] = 6
#end of code
print('b = \n', b)

b = 
 [[1 2 3 4 5]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [1 2 3 4 5]]


Change the first two elements of second column of b into 16

In [147]:
# write your code here (~ 1 line of code)
b[1,0:2] = 16
#end of code
print('b = \n', b)

b = 
 [[ 1  2  3  4  5]
 [16 16  6  6  6]
 [ 6  6  6  6  6]
 [ 1  2  3  4  5]]


Change every 4 of r (if any) into 40

In [174]:
# write your code here (~ 1 line of code)
i = np.where(r==4); r[i]=40
#end of code
print('r = \n', r)

r = 
 [[ 1.38929058  1.80730647  1.00146972 -1.69803038 -2.01050893]
 [-0.56845801  0.95160039  0.24338586 -1.41281285 -0.39722562]
 [ 1.99804627 -0.94393919  0.63238182 -1.25188772  0.0833394 ]
 [ 1.51049691  0.47203351  0.80153071  0.42882538 -0.86378836]]


### 7. Array Manipulation

Find traspose of b

In [50]:
# write your code here (~ 1 line of code)
b_trans = b.T
#end of code
print('transpose of b = ', b_trans)

transpose of b =  [[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]


Flatten the array c

In [177]:
# write your code here (~ 1 line of code)
c_flat = c.flatten()
#end of code
print('c (flat) = ', c_flat)

c (flat) =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Append r into b

In [181]:
# write your code here (~ 1 line of code)
b_new = np.append(b,r)
#end of code
print(' New b = \n', b_new)

 New b = 
 [ 1.          2.          3.          4.          5.         16.
 16.          6.          6.          6.          6.          6.
  6.          6.          6.          1.          2.          3.
  4.          5.          1.38929058  1.80730647  1.00146972 -1.69803038
 -2.01050893 -0.56845801  0.95160039  0.24338586 -1.41281285 -0.39722562
  1.99804627 -0.94393919  0.63238182 -1.25188772  0.0833394   1.51049691
  0.47203351  0.80153071  0.42882538 -0.86378836]


Congratulations ! You did it :)